import assert from 'node:assert/strict';

// Read-only checks against an already-running development server. No model calls.
const base = process.env.LOCAL_TEST_URL || 'http://localhost:3000';
const legacyProject = '00000000-0000-4000-8000-000000000002';
const demoProject = '00000000-0000-4000-8000-000000000005';
const legacyFetch = (url, options = {}) => fetch(url, { ...options, headers: { Cookie: `ps02_project=${legacyProject}`, ...options.headers } });
const defaultPage = await (await fetch(base)).text();
assert.ok(defaultPage.includes('River Restoration'), 'Demo is the default project');
for (const name of ['Site A', 'Site B', 'Site C']) assert.ok(defaultPage.includes(name), `Demo contains ${name}`);
const demoEvidence = await (await fetch(`${base}/evidence`)).text();
const api = await fetch(`${base}/api/projects/00000000-0000-4000-8000-000000000002/search?llm=off`);
assert.equal(api.status, 200);
const { results } = await api.json();
const asset = results.find(row => row.status === 'review') || results[0];
assert.ok(asset, 'A stored asset is required for this read-only smoke check');
for (const row of results) assert.ok(!demoEvidence.includes(`/evidence/${row.id}`), 'Demo does not show legacy evidence');
const pages = ['/', '/evidence', '/review', '/search', '/upload?test=core', '/projects/new', `/evidence/${asset.id}`, '/search?q=people&llm=off'];
const rendered = new Map();
for (const path of pages) {
  const response = await legacyFetch(base + path);
  assert.equal(response.status, 200, path);
  const html = await response.text();
  rendered.set(path, html);
  assert.equal((html.match(/<nav[^>]*aria-label="Project navigation"/g) || []).length, 1, `${path}: shared navigation`);
  for (const href of ['/', '/evidence', '/review', '/search', '/upload']) assert.ok(html.includes(`href="${href}"`), `${path}: ${href}`);
}
assert.ok(rendered.get('/').includes('Activity breakdown'));
assert.ok(rendered.get('/').includes('Project timeline'));
assert.ok(rendered.get('/').includes('action="/search"'));
const detail = rendered.get(`/evidence/${asset.id}`);
for (const text of ['Trust checklist', 'AI assessment', 'Transformation', 'Original']) assert.ok(detail.toLowerCase().includes(text.toLowerCase()), text);
assert.ok(detail.includes('Not checked'), 'Unconfigured project date check is not a failure');
assert.ok(detail.includes('Review site assignment'));
for (const name of ['name', 'organization', 'campaign_type', 'location', 'start_date', 'end_date', 'description', 'activities']) assert.ok(rendered.get('/projects/new').includes(`name="${name}"`), `New project field ${name}`);
for (const text of ['Batch context', 'Activity hint', 'Date']) assert.ok(rendered.get('/upload?test=core').includes(text), `Batch field ${text}`);
assert.ok(rendered.get('/search?q=people&llm=off').includes(`/evidence/${asset.id}`));
assert.ok(rendered.get('/search?q=people&llm=off').includes('Evidence status and pipeline state'));
const beyondEnd = await (await legacyFetch(`${base}/evidence?page=9999`)).text();
assert.ok(beyondEnd.includes('No assets on this page.'), 'Out-of-range pages retain the real total');
const filtered = await (await legacyFetch(`${base}/evidence?status=${asset.status}`)).text();
assert.ok(filtered.includes(`/evidence/${asset.id}`));
for (const other of results.filter(row => row.status !== asset.status)) assert.ok(!filtered.includes(`/evidence/${other.id}`), 'Status filter excludes unrelated statuses');
for (const query of ['status=not-a-status', 'from=2026-03-31&to=2026-03-01', 'from=2026-02-30']) {
  const response = await legacyFetch(`${base}/evidence?${query}`);
  const html = await response.text();
  assert.ok(html.includes('Check your filters'), query);
}
const missing = await legacyFetch(`${base}/evidence/00000000-0000-4000-8000-000000000999`);
assert.equal(missing.status, 404);
const states = await fetch(`${base}/api/assets/states?project=${legacyProject}&ids=${results.map(row => row.id).join(',')}`);
assert.equal(states.status, 200);
assert.equal(states.headers.get('cache-control'), 'no-store');
const stateRows = (await states.json()).assets;
assert.equal(stateRows.length, results.length);
for (const row of stateRows) assert.deepEqual(Object.keys(row).sort(), ['id', 'pipeline_state', 'status']);
assert.equal((await fetch(`${base}/api/assets/states?ids=invalid`)).status, 400);
const isolatedStates = await (await fetch(`${base}/api/assets/states?project=${demoProject}&ids=${asset.id}`)).json();
assert.deepEqual(isolatedStates.assets, [], 'Polling cannot cross project boundaries');
const post = (path, body) => fetch(base + path, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: base }, body: JSON.stringify(body) });
const selection = await post('/api/projects/select', { project_id: legacyProject });
assert.equal(selection.status, 200);
assert.ok(selection.headers.get('set-cookie')?.includes(`ps02_project=${legacyProject}`));
assert.equal((await post('/api/projects/select', { project_id: '00000000-0000-4000-8000-000000000999' })).status, 404);
assert.equal((await post('/api/projects', { name: '' })).status, 400);
assert.equal((await post(`/api/projects/${demoProject}/sites`, { name: '' })).status, 400);
const demo = await (await fetch(`${base}/api/projects/${demoProject}`)).json();
assert.equal(demo.project.start_date, '2026-01-01');
assert.equal(demo.project.end_date, '2026-06-30');
const paramsToSign = { timestamp: Math.floor(Date.now() / 1000), upload_preset: 'ps02_core', asset_folder: `ps02/${demoProject}`, context: `project=${demoProject}|ps02_analysis_tier=bulk|site_id=${demo.project.sites[0].id}|activity_hint=river_cleanup|batch_date=2026-03-01` };
const signed = await post('/api/upload-signature', { paramsToSign });
assert.equal(signed.status, 200);
assert.ok(typeof (await signed.json()).signature === 'string');
assert.equal((await post('/api/upload-signature', { paramsToSign: { ...paramsToSign, context: paramsToSign.context.replace('bulk', 'demo') } })).status, 400);
console.log(`Rendered page checks passed: ${pages.length} pages, demo default/sites, legacy selection, project isolation, forms/batch fields, shared navigation, detail trace/tri-state checklist, unchanged search links/badges, invalid inputs, project cookie and batch signature validation. No AI/media/review writes.`);
