import Link from 'next/link';
import { getDashboard, STATUSES } from '../lib/project-views.mjs';
import { readable, formatDate } from './components/evidence-parts';
import { selectedProjectId } from '../lib/active-project';
import SiteForm from './components/site-form';

export const dynamic = 'force-dynamic';
export default async function Dashboard() {
  const { project, statuses, activities, timeline, totals } = await getDashboard(undefined, await selectedProjectId());
  if (!project) return <main className="evidence"><p className="eyebrow">PS02 / PROJECT OVERVIEW</p><h1>Project not available.</h1><div className="panel search-empty"><h2>No project selected.</h2><p>Set up a project before collecting evidence.</p><p><Link href="/projects/new">Create a project →</Link></p></div></main>;
  const counts = Object.fromEntries(statuses.map(row => [row.status, row.count]));
  return <main className="evidence dashboard"><p className="eyebrow">PS02 / PROJECT OVERVIEW</p><h1>{project.name}</h1><p>{project.description || 'A traceable record of field activity, from original media to reviewed evidence.'}</p>
    <dl className="project-facts"><div><dt>Organization</dt><dd>{project.organization || 'Not specified'}</dd></div><div><dt>Location</dt><dd>{project.location || 'Not specified'}</dd></div><div><dt>Campaign</dt><dd>{project.campaign_type ? readable(project.campaign_type) : 'Not specified'}</dd></div><div><dt>Project dates</dt><dd>{formatDate(project.start_date)} → {formatDate(project.end_date)}</dd></div></dl>
    <form action="/search" className="dashboard-search"><label htmlFor="dashboard-query">Find a moment in your evidence</label><div><input id="dashboard-query" name="q" type="search" maxLength={1000} placeholder="Volunteers planting trees near the river" /><button type="submit">Search evidence</button></div></form>
    <section aria-labelledby="status-heading"><div className="search-results-heading"><h2 id="status-heading">Evidence overview</h2><p>{totals.assets} assets · {totals.frames} derived video frames included</p></div><div className="status-grid">{STATUSES.map(status => <Link className={`stat-card stat-${status}`} key={status} href={`/evidence?status=${status}`}><span className={`status status-${status}`}>{status}</span><strong>{counts[status] || 0}</strong><span>View evidence →</span></Link>)}</div><p className="small muted">{totals.processing} {totals.processing === 1 ? 'asset is' : 'assets are'} queued or being analyzed. Open evidence to follow live pipeline states.</p></section>
    <div className="dashboard-columns"><section className="panel" aria-labelledby="activities-heading"><div className="section-heading"><h2 id="activities-heading">Activity breakdown</h2><Link href="/review">Review queue →</Link></div><p className="small muted">Accepted and awaiting-review assets have separate counts. The totals include every asset record, video frames too.</p>{activities.length ? <div className="table-scroll"><table><thead><tr><th scope="col">Activity</th><th scope="col">Accepted</th><th scope="col">Review</th></tr></thead><tbody>{activities.map(row => <tr key={row.activity || 'unknown'}><th scope="row">{row.activity ? <Link href={`/evidence?activity=${encodeURIComponent(row.activity)}`}>{readable(row.activity)}</Link> : 'Unclassified'}</th><td>{row.accepted}</td><td>{row.review}</td></tr>)}</tbody></table></div> : <p className="muted">No activities recorded yet.</p>}</section>
    <section className="panel" aria-labelledby="sites-heading"><h2 id="sites-heading">Project sites</h2>{project.sites.length ? <ul className="site-list">{project.sites.map((site) => <li key={site.id}><Link href={`/evidence?site=${site.id}`}>{site.name} →</Link></li>)}</ul> : <p className="muted">No sites have been assigned yet.</p>}<SiteForm projectId={project.id} /><Link className="button-link" href="/upload">Upload evidence →</Link></section></div>
    <section aria-labelledby="timeline-heading"><div className="search-results-heading"><h2 id="timeline-heading">Project timeline</h2><p>Grouped by capture day · UTC · all statuses</p></div><p className="small muted">Built from the whole collection. Photos and videos are source assets; derived frames get their own count.</p>
      {timeline.length ? <ol className="timeline">{timeline.map(day => <li key={day.day || 'unknown'}><div className="timeline-date">{day.day ? <Link href={`/evidence?from=${day.day}&to=${day.day}`}>{formatDate(day.day)}</Link> : 'Capture date unknown'}</div><div><p><strong>{day.photos}</strong> photos · <strong>{day.videos}</strong> videos{day.frames > 0 && <> · <strong>{day.frames}</strong> derived frames</>}</p><p className="small muted">{day.activities?.length ? day.activities.map(readable).join(' · ') : 'Activity awaiting classification'}</p></div></li>)}</ol> : <div className="panel search-empty"><h3>Your timeline starts with evidence.</h3><p>Uploads show up here as soon as Cloudinary reports them.</p></div>}
    </section>
  </main>;
}
